### ISSUE TITLE
Edit comments

### ISSUE THREAD

**Issue by umputun** [umputun/remark#13]
This functionality already supported by backend and should be implemented on UI side

**Comment by Shchvova** [comment]
Thanks! Having access to original markdown would possibly allow to extend rendering on client side with syntax highlighting (#32) or embedding mathematical formulas (#31) with libraries like 

Personally, I like option 1 just because it keeps things simple on client side in simplest case. If user wants to get nice formatted github code blocks or mathjax, they can do that w/o branching the project

**Comment by umputun** [comment]
Comment struct extended with `orig` field. 

Btw, it may also fix #3 as it calculated comment's size after md rendering. Switched this size check to `orig`.

**Comment by igoradamenko** [comment]
We've implemented this feature :-)
