### ISSUE TITLE
Add wordpress comment import.

### ISSUE THREAD

**Issue by cooperaj** [umputun/remark#156]
I'm looking to move my existing comment from wordpress to discuss. I *could* export from wordpress to discuss and then from discuss to remark but it'd be nice to cut out the middle man :)

**Comment by umputun** [comment]
Do you have WP spec for their export format? Also, some real example of exported comments will help as well

**Comment by akosourov** [comment]
It looks like Wordpress can export comments in different formats as XML or CSV. Suppose the db structure is [here](https://codex.wordpress.org/Database_Description#Table:_wp_comments). 
If we find real examples of exported comments I can try to take this one, looks like similar to `Disqus.Import`

**Comment by umputun** [comment]
yeah, should be doable and not too hard. In addition to the new Importer implementation, you will need some minor change in `rest.Migrator.importCtrl`

**Comment by akosourov** [comment]
@cooperaj Could you give an example of WP exported comments?

**Comment by cooperaj** [comment]
Oh sure. Do you have somewhere I can put them? Or, at least somewhere I can
send a link to them? A comment export is essentially a full export of your
wordpress instance and I don't really want that up on github :)

**Comment by akosourov** [comment]
@cooperaj I think you can send email with comments to @umputun and to me (because I'm going to solve it). You can find email addresses on github user's page

**Comment by cooperaj** [comment]
@akosourov I've emailed an export of my blog to both your addresses :)

**Comment by akosourov** [comment]
@cooperaj yeah, see thanks
@umputun May I implement this ticket?

**Comment by akosourov** [comment]
@cooperaj due to #182 merged remark has WP importer. Try to import all comments to remark and  leave feed back, please. Also check the [instruction](https://github.com/umputun/remark#initial-import-from-wordpress) about importing from WP, and if it is not so obvious please open PR to update it or simple say what is wrong

**Comment by cooperaj** [comment]
👍 LGTM

With the caveat that I used the same export that you developed against so may not get to see any hidden issues.

[Some imported comments visible here](https://realmenweardress.es/2016/07/deploying-rancheros-on-vultr-instances/)

**Comment by cooperaj** [comment]
Though as you can see on the last comment on that page the markdown processing hasn't quite worked.

**Comment by umputun** [comment]
> The export file contains newlines just fine so it looks like the import is what removed them.

@akosourov you do it here https://github.com/umputun/remark/blob/master/backend/app/migrator/wordpress.go#L151

I think you just duplicated logic I have for Disqus but it can be not applicable for WP files. The reason why I had this `cleanText` as a part of Disqus (you promoted it to top-level func in order to hit it from WP importer) is crazy output Disqus generating. Sometimes it has a bunch of \n and bunch of \t with no recognizable pattern.

If WP doesn't suffer from the same issue such cleanup not needed.

**Comment by akosourov** [comment]
@umputun 
My goal was to make common logic for converting WP and Disqus so `cleanText` were shared between them. Yeah, I see for WP it is not suitable (I suppose) and I can return it back. Or clean only multiple `\n` like `\n\n\n` 

What about markdown converting?  Maybe make more common logic for "text to html" converting and put it in [DataService.Create](https://github.com/umputun/remark/blob/master/backend/app/store/service/service.go#L33)
I see [preview](https://github.com/umputun/remark/blob/master/backend/app/rest/api/rest_public.go#L84) and [create](https://github.com/umputun/remark/blob/master/backend/app/rest/api/rest_private.go#L47) use the same code. And Importer could use it

**Comment by umputun** [comment]
The part about markdown converting is not clear to me. Is WP even has comments in markdown?  If all we need is dealing with \n properly the cleanText removal (or replacing multiple \n\n\n... to a single \n) should do it.

Regarding changing `DataService.Create` to apply md parsing - I don't think it will be the right place. DataService.Create wraps engine.Create and deals with additional validation and sanitizing, but generally doesn't alter the content. If we change text by running md convertor it may have some unexpected side-effects, like each backup/restore producing changed text. In addition, I consider md parsing as something above DataService level.

**Comment by akosourov** [comment]
@umputun Yeah, I've found out WP [supports](https://en.support.wordpress.com/markdown/) markdown  in comments if it is enabled.

>  I consider md parsing as something above DataService level

Maybe add `DataService.AlterText` function (method) and this procedure could alter content like:
1. Convert markdown to html
2. Convert img links to proxy
3. Short links
4. Clean multiple \n\n\n to \n\n (or one only see below)

So WP importer could use same logic as remark use when saves comments.

I've sent original comment from  WP exported file on remark demo page to see how remark renders same input. This is [here](https://remark42.com/demo/#remark42__comment-51ae9b17-bd3a-4a0f-b57e-59441031086e). It looks like remark also trims empty rows (I mean `\n\n` to `\n`). In my opinion it could be better to have an opportunity to put at least one empty row. It may improve user experience to have such indent

**Comment by umputun** [comment]
@akosourov the problem I see with this approach is way too many unusual responsibilities added to `DataService`. Currently, markdown to html is a part of rest create & preview controllers, img links to proxy lives in proxy and so on. Moving all of this to `DataService` doesn't feel right. Yeah, technically all of this some kind of "text formatting" but I'd like to keep such formatting as close to consumer (caller) as possible.

Theoretically, a nicer approach may be to import WP indirectly, i.e. pass to WP constructor enough info to allow it submitting comments in the usual way, via rest calls. This won't require much work and refactoring, however, it won't work as of now, because rest calls authentication middleware extracting user info from the token. Even if we make token per user we will run into other issues, like create controller assigning timestamps to comments and so on.

I don't have a good idea how to deal with this yet and not even sure if we really want/need a generic solution here. If we really have to have the same processing path for any text input (rest or import), we may need a new abstraction, something like `CommentFormatter` and pass it to rest, wp imported and any other place we like. 

Anyway, let me think about it and maybe I'll play around this idea on code level to see how it goes.

**Comment by umputun** [comment]
@akosourov I've added `CommentFormater` (see PR #186). It does md processing, link shortening and accepts user-defined `CommentConverter`. This way some external functionality can be passed as needed. See in main.go how it used for image proxy.

I think all you need is to add this thing to your wordpress importer and it should do. Let me know if any confusions.

**Comment by akosourov** [comment]
@cooperaj You can retry to export comments from wp to remark. Due to #192 merged we have MD support for import procedure. Also any content from import procedure should be rendered in common way.
Be aware that import procedure removes all your existing comments

**Comment by akosourov** [comment]
> what is the reason for html.UnescapeString(text)?

I've added it because wp export file contains encoded charaters. It looks like wp encodes such characters like `« ’ " –` and doesn't unescape them in export file.
Here list of encoded characters that I found in example export file:
```
&#039;
&quot;
&amp;
&laquo;
&#8217;
&#8211;
&raquo;
&nbsp;
```
Real example exitsts in test [here](https://github.com/umputun/remark/blob/master/backend/app/migrator/wordpress_test.go#L232)

**Comment by umputun** [comment]
ok, I  guess it won't hurt because `Sanitize` will escape all dangerous elements anyway.

**Comment by cooperaj** [comment]
Mmm, the markdown appears to have worked but I'm still seeing the truncation of newlines. My export file might contain 

```
but pretty much all of them are down to the individual player.

Hm, well this turned into a wall of text didn’t it! I think I’ll stop now!

CWx
```

But the imported comment looks like

```
but pretty much all of them are down to the individual player.Hm, well this turned into a wall of text didn’t it! I think I’ll stop now!CWx
```

See how the new paragraphs are removed and there are now spaces at all in the sentences?

**Comment by umputun** [comment]
@cooperaj this is odd. I see the test for very similar case https://github.com/umputun/remark/blob/master/backend/app/migrator/wordpress_test.go#L83 using this [data](https://github.com/umputun/remark/blob/master/backend/app/migrator/wordpress_test.go#L258)

@akosourov any idea? You can try to add this particular comment, but I bet it will pass. If this is the case you need some changes  in`TestMigrator_ImportFromWP` to test the content (with MD formatting), not just a count.

**Comment by umputun** [comment]
@akosourov - I have added the test

@cooperaj - can't reproduce the issue. Have a new end-to-end test importing from the comment you provided and got properly formatted record

```
 <p>Looks like <a href="http://releases.rancher.com/os/latest" rel="nofollow">http://releases.rancher.com/os/latest</a> is no longer hosted - installs using this <code>base-url</code> are failing.</p>\n\n<p>I switched to Github with success:</p>\n\n<pre><code>set base-url https://github.com/rancher/os/releases/download/v1.1.1-rc1\n</code></pre>\n\n<p>Thanks for the article!</p>\n
```

**Comment by akosourov** [comment]
@umputun Yes, this is odd for me too. Perhaps my test passed because md contains backticks that conflicts with go string literals " ` " so I used to combine string using +. I mean this
https://github.com/umputun/remark/blob/master/backend/app/migrator/wordpress_test.go#L306
Maybe it adds additional \n

**Comment by umputun** [comment]
@akosourov In my test, I have enforced backticks by [strings.Replace](https://github.com/umputun/remark/blob/master/backend/app/rest/api/migrator_test.go#L51) and this is [the comment](https://github.com/umputun/remark/blob/master/backend/app/rest/api/migrator_test.go#L313)

**Comment by cooperaj** [comment]
I'm not sure whats going on then. I just removed my DB file and ran the import on a fresh database and I'm still seeing the paragraphless version. But I am seeing the markdown. 

I'll rebuild my docker container and see if theres anything I missed but it was built yesterday from a fresh pull to my knowledge.

**Comment by umputun** [comment]
@cooperaj - thx for the detailed report. The good news - I was able to reproduce the issue by doing a complete import. Still have no idea what the root cause, but this is an easy part :) hopefully, fill figure it soon.

**Comment by umputun** [comment]
yay!

<img width="476" alt="mkp0j-201808-17160927-ouhsb" src="https://user-images.githubusercontent.com/535880/44289066-4f790680-a238-11e8-8c8f-383dda72c4f7.png">

This was a tricky one. The reason why none of our tests were able to catch it is very ... refreshing :) 
There was no error in the code, and it worked just fine. The issue is the way `import-wordpress.sh` script submitted the data - instead of `-d` it just needs `--data-binary`.

@akosourov - I know you copied this script from `import-disqus.sh` and modified a little bit. However, for Disqus import EOL (or lack of them) inside of a comment changes nothing as they export rendered html snippet.

**Comment by akosourov** [comment]
@umputun  oh, I didn't know the difference between `curl --data ...` and `curl --data-binary ...`
Just thought that `-d` put data in body and doesn't do any processing with input data.
Thanks a lot, it's really helpful experience for me

**Comment by umputun** [comment]
@cooperaj - if you fine with the latest fixes feel free to close this ticket.

**Comment by cooperaj** [comment]
All looks great to me. Sorry for taking so long to investigate the fix, been super busy :)
