### ISSUE TITLE
Vote result is not storing if you change your decision too fast

### ISSUE THREAD

**Issue by ivanzolotov** [umputun/remark#17]
If you click "+1", but later change your decision, you can make two "−1" clicks. If you make these clicks fast, UI responses properly, decreasing votes by 2. But a few moments later vote count increases by 1.

**Comment by igoradamenko** [comment]
Actually, UI updates voting score before voting request (like an optimistic UI) and after (just to show actual information). But, yeah, there was a request race condition. Now it fixed, and vote requests are processing one by one.

BTW, it's still possible to get “wrong” voting score, because of intermediate values. For example:

```
user presses +1 → score updates to +1
user presses −1 → score updates to 0
user presses −1 → score updates to −1
request for +1 are processed → score updates to +1 (because it's true current value)
first request for −1 are processed → score updates to 0
second request for −1 are processed → score updates to −1
```

So, at the end we have true value. And I'm not sure that we need to make UI more complex due to additional processing of these intermediate values. Nevertheless I will try to fix it in the future when we rewrite UI's store.

But, for now the race condition is fixed. Thanks!
