### ISSUE TITLE
Add "Cancel" button

### ISSUE THREAD

**Issue by shalugin** [umputun/remark#18]
Сейчас как и на дискусе - только обновление страницы возвращает текстовое поле в исходное положение. А если стереть введённый текст - то поле становится с красным бордюром.
Было бы удобно нажать кнопку "Cancel" и отменить ввод комментария

**Comment by igoradamenko** [comment]
But for what?

**Comment by shalugin** [comment]
Всегда можно передумать

**Comment by igoradamenko** [comment]
We have “Cancel” button for replies, because reply form changes threads UI: you can open it (using “Reply”) or close it (using “Cancel”).

But you can't open or close main comment form. If you want to remove anything from it — just remove it using Delete, Backspace, ← button on mobiles and so on.

I'm not sure that it's OK to add one more button / link to the main form because of this case. It's so edgy.

**Comment by igoradamenko** [comment]
Ah, that's the root of your issue :-)

It's default FF border color in our case, because we use some HTML tricks. Actually, AFAIK it's legacy and we haven't used it anymore.

So I will remove red border from FF, thanks.

**Comment by igoradamenko** [comment]
Fixed.
