### ISSUE TITLE
Collapse issue

### ISSUE THREAD

**Issue by shalugin** [umputun/remark#20]
Go to demo site and collapse comment. https://remark42.com/demo/#remark42__comment-d4176b05-d69d-447a-8d2e-75d2cd933f98

It seems that max comment level for show is 5, but it's not real level.
You can hide comments that have the same level.

Probably it's a bug.

**Comment by umputun** [comment]
I don't think so. Max comment level is not really limited (just visually) and collapse should hide replies on any level exactly like it is doing now. However, it is confusing a little bit, not because of collapse behavior but due to lack of visual indication "replied to". This part was discussed with @igoradamenko and he will add such indication soon.

**Comment by igoradamenko** [comment]
Yep, it's not a bug.

We decided to add button `Go to parent comment`, so if someone is confused about indication of levels they can find parent comment by clicking on this button.

I'm not sure that we need to add more indication. I think it would make UI noisier.
