### ISSUE TITLE
Show more - do we even need it?

### ISSUE THREAD

**Issue by umputun** [umputun/remark#25]
Some users suggested limiting the number of comments we render by default and show them all as "more" clicked. Personally, I don't really like this idea but open to suggestions/justifications.

**Comment by igoradamenko** [comment]
I also don't like it, but sometimes it's useful. For example for long threads on mobiles. When all comments are rendered, interaction with UI is slow because of it. I will try to optimise it, but I'm not sure that it's possible to do it fast with any length of thread. 

Also short threads load faster by any network, so maybe it's a good solution to do it.

But I'm not sure how to do it correctly. For instance, we can load first 10 comments sorted by best, and after some minutes we will want to load 10 more. What if some of them change theirs position in best-sorted list? Should I send you rendered comments' ids? Maybe it's not a big problem, because we talk about comments (not about money-making-things), but it exists.

**Comment by umputun** [comment]
I thought all of this just on your side. I.e. you will get all comments as usual but will show only limited number by default.

**Comment by umputun** [comment]
I don't like this "More" button on the desktop. Maybe we should have this functionality on mobile-only view?

**Comment by igoradamenko** [comment]
> should we make it smarter to understand collapsed #43 ? I mean, if a part is collapsed at the load time we may exclude all of those from your max count.

It's possible, but makes UI logic more complex, so I don't want to add it right now. Let's see to usage. If it's a problem, we will change it.

> this max number should be configurable on UI side with some default and ability to override in comments widget params.

OK, I've added it in 5fe7854.

> I don't like this "More" button on the desktop. Maybe we should have this functionality on mobile-only view?

OK, right now (by 81b881a) we add this button only on mobile devices. Also I think that it's a “workaround” for your first idea about understanding collapsed items. I mean, now there is no such problem on desktop.
