### ISSUE TITLE
Hanlde limiter rejection on UI side

### ISSUE THREAD

**Issue by umputun** [umputun/remark#256]
With https://github.com/umputun/remark/commit/2a3051c620e775516e33a6378969a81977476d6b I have added more aggressive limiter/throttler for update/create requests. It covers
Put("/comment/{id}"), Post("/comment"),Put("/vote/{id}") and  Post("/deleteme"), all under `/api/v1` 

Most of those limits are really hard to trigger from UI, except vote. Currently, if the user doing massive voting and got throttled, there is no indication of this rejection on UI side. For the user, it looks like all the votes passed/accepted, but after a refresh, they will see the real results.

Not sure what the right/best way to handle it on UI side.

@igoradamenko @Reeywhaar  - any bright ideas?

**Comment by igoradamenko** [comment]
If it heads to prevent aggressive requests, then maybe it's fine that user doesn't get proper feedback from UI? Let him think that everything is fine ¯\_(ツ)_/¯

**Comment by umputun** [comment]
and another one, not related directly but similar: blocked user rejected without any explanation/indication in login. Not even "authentication rejected" or smth like this.

**Comment by umputun** [comment]
@igoradamenko maybe not a bad idea, and the best part of this - nothing more to do ;)

**Comment by Reeywhaar** [comment]
Well, `Put("/comment/{id}"), Post("/comment")` already handled, I think standard error will be shown, like [here](https://user-images.githubusercontent.com/884649/51277542-f846b000-19e8-11e9-9a59-42ec3ed11720.png) but `Something went wrong. Please try again a bit later.`, though this message can be clarified.

As for votes I think standard way is to introduce notification component like [here (click "show")](https://reeywhaar.github.io/reey-notifications/#different-levels). Preact component exists in [rtnews-ui](https://github.com/radio-t/rtnews-ui/blob/master/src/notifications.tsx) for example. Though one complication is that everything works in iframe, and we'll have to make third iframe (comments, user comments, notifications) with [data](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs) url and work this way through pushing messages. Or maybe try to work it out without iframe. 

Another way is to show something right in place of voting buttons, but I'm afraid that response from server could arrive late, already after user voted and scrolled somewhere so buttons get behind viewport and notification will be unnoticed.

I can partially agree with @igoradamenko. No one died because of voting system on Reddit yet :-) But I think something should notice user of error in case of network error for example.

**Comment by Reeywhaar** [comment]
Guess, this can be closed as well?
