### ISSUE TITLE
New storage backends

### ISSUE THREAD

**Issue by meln1k** [umputun/remark#319]
If I want to integrate a custom storage backend, what parts do I need to implement?

So far it looks like I can start with something similar to https://github.com/umputun/remark/blob/master/backend/app/store/engine/mongo.go, but it is not clear how to implement a backend for storing images.

Are there any recommendations or best practices?

**Comment by umputun** [comment]
Hi. As of now there is no documentation explaining how to deal with external storages. Example of mongo implementation is the closest one. In addition to the core storage (i.e. store/engine) you will need 2 more things:

- storage for uploaded images  (implement 1store/image/image.go/Store` interface)
- storage for user's avatars. This part is external library accepting user defined implementations - see https://github.com/go-pkgz/auth/blob/master/avatar/store.go

Another thing you may want is a store for admin data and this is in store/admin.

Generally I would recommend not to do it yet. The current way to add storages is not too friendly and need way too much efforts. I'm in the process of migrating all of this to some pluggable architecture allowing much simpler extensions. As a part of this process I'll move mongo to such a plugin (bolt will stay as a core implementation inside) and will provide an example of some trivial user-defined storage covering all areas.

**Comment by umputun** [comment]
The new backend interface has been [merged](https://github.com/umputun/remark/pull/353) into master. Instead of the insane amount of function we used to have, all low-level storage functionality consolidated into just a [few generalized methods](https://github.com/umputun/remark/blob/master/backend/app/store/engine/engine.go#L18) and several higher-level operations were moved to the common [store/service](https://github.com/umputun/remark/tree/master/backend/app/store/service).

In order to allow users to bring their own storages, I have added a special layer for RPC-like calls (see [/backend/app/remote](https://github.com/umputun/remark/tree/master/backend/app/remote)). For convenience, it also includes the code for [user's plugin](https://github.com/umputun/remark/blob/master/backend/app/remote/server.go), i.e. server/remote/plugin side/dispatcher. Support of such custom storages was added to options (cli params and env) as well.

Both new interface and RPC protocol need some detailed documentation and examples (work in progress), but generally speaking, it should be clear from the code what the protocol is and how to use it. I'm planning to add full demo implementation of the custom storage backend (in-memory storage) this weekend.

**Comment by umputun** [comment]
I have added [an example](https://github.com/umputun/remark/tree/master/backend/_example/memory_store) implementation of alternative storage.
