### ISSUE TITLE
private discussions?

### ISSUE THREAD

**Issue by jcw** [umputun/remark#327]
It was really nice to find this self-hosted comment system. Thanks for creating and sharing it.

Would it be possible to use this for private discussions as well? I'm looking for a self-hosted setup to have small chat sessions between a few developers, some of which would be about the security of a new (open source) system I'm working on. My concern is that part of this discussion needs to stay private, so that we can properly evaluate our security concerns. It would be nice if  I could avoid creating a full-scale closed forum for just these brief chats.

I suppose one could use HTTPS plus basic web access authentication, but perhaps there are better ways to go about this? Has this been on the radar for this project or is out of its scope?

**Comment by umputun** [comment]
Are you asking about ability to host completely private commenting system? I.e. not selectively private, but everything is hidden by default? And the use case it to make a page like "security incident" which is private by itself and showing the content (and comments) to special group of users only?

**Comment by jcw** [comment]
I think what I'm aiming for is a secure section (not accessible to guests, only to specific people). There are probably different scenarios, such as what you describe (e.g. a user sharing a comment with more personal details in it for support) - for me, the key is to be able to discuss things with a specific group, preferably in such a way that you don't accidentally "open up" sensitive info in follow-up discussion.

I know I'm being vague, but at this stage I'm really still exploring ideas. What I don't want is a full-fledged forum, and it really needs to be self-hosted. As I said, maybe it's not really a "remark" topic.

**Comment by umputun** [comment]
Generally speaking, remark42 doesn't have "read permission", i.e. discussions are readable by everyone by design. The only realistic workaround I can imagine is to host a dedicated instance of remark42 (and the page itself) behind some additional (external) auth, like basic auth. This will be kind of ugly in practice but should work.

Setup such configuration should be trivial, i.e. a few changes in nginx. Theoretically you can even avoid a dedicated instance of remark42 for such private comments by adding basic auth for specific API calls, but making a separate one will be safer and easier.

_ Pls note - it is possible to extend remark's auth with "Direct providers" passing user info from third-party auth gateway into remark42 in a way similar to anonymous support._

From my side adding the ability so mark some discussions as private is not a trivial thing to do and, most likely, somewhat exotic. I'll think about it and maybe will figure some easy solution.

**Comment by jcw** [comment]
Ok, clear, many thanks. We can probably close this issue for now.
