### ISSUE TITLE
please add vk & yandex oath

### ISSUE THREAD

**Issue by bzdel** [umputun/remark#34]
если возможно, добавьте, пожалуйста

**Comment by umputun** [comment]
Sorry, but I will not support VK oauth. For Yandex - tried to do it but run into multiple issues mostly due to lacking and incomplete documentation. I have nothing against Yandex oath, but this won't be a priority. If someone wants to add Yandex to the list of providers (see [auth/providers.go](https://github.com/umputun/remark/blob/master/app/rest/auth/providers.go)) I'll integrate it.

**Comment by anatolym** [comment]
@bzdel, yandex oauth was added. I think we can close this issue.

**Comment by sergio-fry** [comment]
@umputun Could you explain why don't you want to support vk ? Looks like go oauth2 supports vk provider as well.

**Comment by sergio-fry** [comment]
Huh! Looks like it has been implemented after this issue was closed: golang.org/x/oauth2/vk

**Comment by niocncn** [comment]
Add vk.com support please

**Comment by umputun** [comment]
why? We have many popular and more "generic" providers already in place. What is the use case requiring to have vk in addition?

**Comment by niocncn** [comment]
Because Vk is very popular social network in east europe. Your question is the same as "why do we need twitter provider if we have facebook".
