### ISSUE TITLE
/api/v1/admin/blocked is broken

### ISSUE THREAD

**Issue by Reeywhaar** [umputun/remark#341]
I see strange behaviour of `/api/v1/admin/blocked`:

* the `name` is empty here
* I'm not sure if user id is right. `banned_joe` logged in with `dev` provider
```
get /api/v1/admin/blocked

200 OK
[{"id":"banned_joe","name":"","time":"2019-06-16T15:02:16.860926708-05:00"}]
```

* Block works in terms that comments fetched after block don't contain blocked user
```
put /api/v1/admin/user/banned_joe_2?block=1&ttl=10080m&site=remark

200 OK
{"block":true,"site_id":"remark","user_id":"banned_joe_2"}
```

* Trying to unblock someone results on 200 OK, but comments fetched after unblock still don't contain unblocked user
```
put /api/v1/admin/user/anonymous_b3f594e10a9edcf5413cf1190121d45078c62290?block=0&site=remark

200 OK
{"block":false,"site_id":"remark","user_id":"anonymous_b3f594e10a9edcf5413cf1190121d45078c62290"}
```

**Comment by umputun** [comment]
I don't think it is broken. Some details to support my claim:

> the name is empty here

 This may happen only in one case - the blocking was requested for userID without any comments or to incorrect userID, which is technically the same. In this case, we don't have any idea what the name is because there is no place in the system we keep user_id:name information specifically. The only source for such info is a comment. This is [the code](https://github.com/umputun/remark/blob/master/backend/app/store/engine/bolt_admin.go#L233) doing the association from the blocked user's list. As you can see it uses ID to get one comment for this userID and gets the name from the comment.

> Trying to unblock someone results on 200 OK, but comments fetched after unblock still doesn't contain unblocked user

Blocking was changed some time ago to be a destructive action, as a part of #332 (6e12122e444ed86650285b255bd87d660b10bf3c). To be precise this is [the code](https://github.com/umputun/remark/blob/master/backend/app/rest/api/admin.go#L150). So, blocked user, regardless of temporary or permanent status, gets deleted and such delete means deleting user's comments.

**Comment by Reeywhaar** [comment]
Hm, can you please update the docs on blocking/unblocking api (or there is no unblocking anymore?), so I can update ui.

**Comment by umputun** [comment]
it has nothing to with unblocking. There is unblocking, and it means - user allow to write/update comments again.

**Comment by umputun** [comment]
> Nope, user had one comment.

checking, is so can be a bug somewhere on the backend

**Comment by Reeywhaar** [comment]
Took me time to understand what you mean about unblocking and user comments but I got it. Ok, then.

**Comment by umputun** [comment]
ok, I figured why we lost names. This is an unexpected side effect of deleting comments due to blocking. After the delete, there are no comments to use for id-to-name mapping. Checking how to deal with it ...

**Comment by umputun** [comment]
This one should be fine now. @Reeywhaar if you ok with the fix feel free to close.

**Comment by Reeywhaar** [comment]
Looks fine now
