### ISSUE TITLE
REMARK_PORT not changed

### ISSUE THREAD

**Issue by BarryRufer** [umputun/remark#466]
```
docker run \
    -d \
    --name comments \
    -e "REMARK_URL=https://comments.com" \
    -e "SITE=comments_com" \
    -e "SECRET=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 32 | head -n 1)" \
    -e "AUTH_ANON=true" \
    -e "REMARK_PORT=4000" \
    -e "EMOJI=true" \
   --restart always \
   --network comments \
    -v /home/comments.com/remark:/srv/var \
    umputun/remark42:latest
```

8080, but I set 4000

![изображение](https://user-images.githubusercontent.com/57297188/68253095-c3ffb700-002f-11ea-9a23-4164fe3b7878.png)

**Comment by BarryRufer** [comment]
Hmm, but Nginx connected on 4000 port.

**Comment by BarryRufer** [comment]
![изображение](https://user-images.githubusercontent.com/57297188/68254296-e6470400-0032-11ea-84b4-ee6de80feaf2.png)

**Comment by umputun** [comment]
-e (enviroment) doesn't define what port docker exposes. In order to change it, you should change port mapping (`ports` section in compose). Practically, if you run remark42 from container, you don't need to change `REMARK_PORT` at all.

Nginx connects internally to this port (4000 in your example) and doesn't need anything exposed.
