### ISSUE TITLE
How to change and add parameters after creating a docker container?

### ISSUE THREAD

**Issue by BarryRufer** [umputun/remark#468]
I run contailer `"AUTH_ANON=true"`

After a while, I want to add authorization by email, do I need to rebuild it again? Or can I add without stopping the container?

**Comment by umputun** [comment]
_Pls create a single ticket for your install-related question and avoid making issues for something that is not the actual issue_

I'm not sure why you rebuilt containers instead of pulling from docker hub, but container (prebuilt or made by yourself) is like a "version" of the system. I.e. if you update from source and build by yourself it will include all new functionality we have added since your previous build.

There is no need to build (or pull) in order to change a parameter. You just make a change and restart it with `docker-compose up -d`
