### ISSUE TITLE
Quotes are converted to html characters when editing

### ISSUE THREAD

**Issue by ufian** [umputun/remark#52]
When I tried to open message with quotes for edit, then quotes in message are converted to html characters.

Original mesage
<img width="228" alt="screen shot 2018-05-24 at 2 26 26 pm" src="https://user-images.githubusercontent.com/1496873/40514588-80e0f74a-5f5e-11e8-800e-2e6a891958f5.png">

Edit mode
<img width="294" alt="screen shot 2018-05-24 at 2 26 34 pm" src="https://user-images.githubusercontent.com/1496873/40514592-85abe5be-5f5e-11e8-98f9-6a6e17724c15.png">

**Comment by igoradamenko** [comment]
Now we replace HTML entities in UI, but @umputun, I'm not sure that it's a good idea, because someone can post an example of code with HTML entities inside, and we will replace them, because it's hard to recognise where we need to replace them and where we don't.

So, maybe you should change some settings of sanitizer on backend, to prevent converting symbols like quotes to HTML entities.

**Comment by ufian** [comment]
@igoradamenko Can you temporary store original message before replacing? It helps to keep possibility to edit and show replaced symbols. Also, nobody can inject html code.

**Comment by igoradamenko** [comment]
Nobody can inject HTML code, it's right. But someone can post something like this: https://remark42.com/demo/#remark42__comment-d7b6426c-3bf0-45ab-b626-0a5daa39df21. And they will get space instead of `&nbsp;` when they wants to edit:

<img width="317" alt="screen shot 2018-05-26 at 23 29 32" src="https://user-images.githubusercontent.com/6537798/40579938-e71611e6-613c-11e8-93ad-82a556bd122a.png">

But I don't understand the first part of your message. What do you mean “temporary store before replacing”?

**Comment by umputun** [comment]
I think, "temporary store original message on UI side" is about the comment UI shows locally. I guess UI makes "fake comment" without hitting the server and don't put original to `orig` field? I don't really understand the goal but it sounds like a way to get potential XSS if any other part of UI will try to show this locally saved `orig`.

**Comment by ufian** [comment]
I just mean that UI should use original message for edit (message without replaced of HTML entities).
So I don't understand why that issue required of backend developing.

**Comment by umputun** [comment]
UI uses `orig` filed for edit, and this field [sanitized by backend](https://github.com/umputun/remark/blob/master/app/store/comment.go#L98). So, for UI there is no place to get "message without replaced of HTML entities".

**Comment by igoradamenko** [comment]
@umputun, but what about saving original message? I mean, why is it impossible to save `orig` as it comes from user? Why do you think that we need to sanitize this part of message? If someone wants to send message like this:

```
evil <script>alert('message');</script>
``` 

why can't we save it? I mean, UI doesn't evaluate this code, it doesn't paste it to DOM. It only uses `orig` as a string in textarea value. So I don't see any possible attack with this field. But maybe I'm wrong about it.

So I think we don't need this line: https://github.com/umputun/remark/blob/67baf50b6e641c9910296c067ed63e246f7881d0/app/store/comment.go#L99. We need to sanitize `text` field only.

**Comment by umputun** [comment]
My reasoning is this - currently, there is no way server can store and return potentially dangerous code. If we allow such input and someday we have an alternative UI implementation, this implementation will have to be aware of the danger and deal with this on frontend side. Even with our implementation such `orig` may leak into rendering by accident and cause nasty XSS.

I think the way you addressed it on UI side with unescaping is the better way. Yeah, some extra code involved and some potential extensibility limited, but to me, it feels like a good trade-off.

**Comment by igoradamenko** [comment]
OK, I got it. Let's close the issue in this case :-)
