### ISSUE TITLE
Show user's comment

### ISSUE THREAD

**Issue by umputun** [umputun/remark#59]
This method supported by backend and exposed as `/api/v1/comments?site=radiot&user=disqus_umputun&limit=5`.

We need a way to show those comments on UI.

**Comment by igoradamenko** [comment]
I've added the possibility to get last 10 comments of some user by clicking on his nickname.

There are two points:

1. It's a bit hard to create some modal dialog of something like it. So if we want to get something better, we need to paste another iframe dynamically, which will load user comments. Right now I've just added a new block which contains 10 (or less) user comments and it's placed below user's comment.

2. Right now the endpoint (`/api/v1/comments?site=radiot&user=disqus_umputun&limit=5`) returns object with keys with uppercased first letters. So `Comments` instead of `comments`. I think we need to fix it (and then fix it in the UI).

**Comment by igoradamenko** [comment]
Oh, and this endpoint returns deleted comments. I'm not sure that it's fine:

![image](https://user-images.githubusercontent.com/6537798/41560629-5a33dc38-7350-11e8-904f-b07a824aa625.png)

**Comment by umputun** [comment]
fixe both

**Comment by igoradamenko** [comment]
OK, thanks!
