### ISSUE TITLE
Edit timeout countdown bug on frontend

### ISSUE THREAD

**Issue by Modi34** [umputun/remark#74]
![Alt Text](https://i.imgur.com/ZF72PKW.png)
it happens when system time is wrong.

on my windows 10 install I have a windows bug  - time is always a few hours behind for some reason.
If user time is different from server time this bug occure.
to fix it all you need to do is check that timeout is less than 301

**Comment by umputun** [comment]
I don't see how this <301 check will solve anything. There is no way frontend can accurately adjust local time without syncing with the server in some way.

@igoradamenko this is not a bug but sort of unexpected thingy due to time mismatch. I'm not sure we should do anything about it but if we do - the most straightforward way is to use `Date` header and get that timestamp instead of the local time for the countdown on your side.

**Comment by igoradamenko** [comment]
@umputun, I think you're right about the solution. We will try it.

**Comment by jackburg** [comment]
I'll try to resolve this issue.

**Comment by jackburg** [comment]
To resolve this bug I've calculated time span between server and a client and save it in every comment for future use — in the 'remaining' time for comment editing calculation. This bug appeared in both conditions, when user time is in the past and when it al little bit ahead of the server time. Now everything is working fine. @Modi34 could you please confirm?

**Comment by Modi34** [comment]
@jackburg it works - great job
