### ISSUE TITLE
Add link shortening

### ISSUE THREAD

**Issue by misterioss** [umputun/remark#79]
Looks like a long link is ugly a bit:
<img width="789" alt="screen shot 2018-06-13 at 12 22 17" src="https://user-images.githubusercontent.com/3921977/41342237-7594d496-6f04-11e8-8dcf-ef9e2ff5b082.png">
Disqus version of second link:
<img width="464" alt="screen shot 2018-06-13 at 12 22 57" src="https://user-images.githubusercontent.com/3921977/41342303-93b4622a-6f04-11e8-8c0e-a0582ccba6e2.png">

**Comment by misterioss** [comment]
I was wondering how my published screenshots with nicknames and avatars were compatible with GDPR :(

**Comment by umputun** [comment]
Technically ability to "shorten links" already exists as a part of markdown, i.e., instead of posting `https://www.okta.com/security-blog/2018/06/issues-around-third-party-apple-code-signing-checks/` user can do `[apple signing checks](https://www.okta.com/security-blog/2018/06/issues-around-third-party-apple-code-signing-checks/)`

@igoradamenko - if we want to implement it for naked links what side, yours or mine? Kind of make sense either one as you do the actual rendering but the server does it too in some cases.

**Comment by igoradamenko** [comment]
@umputun, for me it looks like some flag must exist in markdown processor for this. But I can't find anything in https://github.com/russross/blackfriday docs. 

So, I think that it must be on your side definitely, but I'm not sure about difficulty of creating some “middleware” for this.

**Comment by umputun** [comment]
I don't see it either. Probably this can be added to comment.Sanitize to strip long links after rendering. This way it will be work for create, edit and preview automatically. Could be done with some ugly regex or with [goquery](github.com/PuerkitoBio/goquery) we already have as a dependency (used in proxy's image.extract)

@anatolym - want to take care of this one?

**Comment by anatolym** [comment]
@umputun, let me check that. I need couple of days if you don't mind.

**Comment by umputun** [comment]
@anatolym looks good. I have increased `shortURLLen` to 48
