### ISSUE TITLE
Caching for other static assets

### ISSUE THREAD

**Issue by umputun** [umputun/remark#90]
similar to #85 - add client-side caching support into `/web` controller.
@anatolym - let me know if you want to take this one. Should be practically the same as avatar caching or very close.

**Comment by anatolym** [comment]
@umputun, sure, I will take a look at this tonight.

**Comment by anatolym** [comment]
@umputun, we have an issue here.
So now we have following files available in "/web":

```
counter.html
counter.js
embed.js
files
iframe.html
index.html
last-comments.html
last-comments.js
remark.css
remark.js
```
It's a mix of html, js and css files.

`.js` and `.css` files are referenced in `iframe.html` "as-is" using filenames. If we force client-side to cache those files for a specific period of time defined via headers `Cache-Control: max-age=<>` and `Etag` as we do for images that will lead to clinet-side using outdated scripts.
In fact `.js` and `.css` files are actually not static and are being compiled every time on build and might have different content. Therefore we should not enforce client-side cashing as it is implemented now.

There're actualy some workarounds which are common for web-applications (including React ones) to force a client to dump the cache and reload updated static content.
Instead of using the same URIs of `.js` or `.css` in `iframe.html` it should be a variadic URIs generated on each build of application.

**1. Using variadic hash parameter appened to script/stylesheet URIs**
During the build of WebApp all the script/stylesheet will be appended with a hash generated for this build. Script include will look like this in `iframe.html`:
```html
<script type="text/javascript" src="/app.js?002919c32268bac44dc7"></script>
```
Read more https://www.npmjs.com/package/html-webpack-plugin (`hash: true`).

**2. Using a variadic hash suffix in script/stylesheet file names**
It's the same approach as the first one but instead of using a parameter in URI we change script name on each build.
```html
<script type="text/javascript" src="/app.002919c32268bac44dc7.js?"></script>
```
Some hints on this can be found here https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#deployment.

Using any of these approaches will allow us to safly enforce client-side cashing of scripts/stylesheets using `Cache-Control: max-age=<>` header.

As for `.html` it should not be cached for a specific period time but instead follow `ETag` or `If-Modified-Since` (`Last-Modified`) header only (this is already handled by `http.FileServer`).

@umputun, @igoradamenko, what do you think?

**Comment by umputun** [comment]
@anatolym Am I missing something and the only issue is the stale read(s) caused by long caching duration. If so, can we make it shorter, like 5 mins? As far as I understand even such short-time cache will be an improvement compared to the current "no cache at all" situation. This will cause worst-case 5mis dealy in cs/js/html updates, unless user forces reload with smth like cmd-option-R

@igoradamenko - what is the usual caching strategy for such files? Maybe we should't cache them at all?

**Comment by Guria** [comment]
We can't change file names of entry points like embed.js, because scripts that reference them in target pages is out of our control. Probably it is a good idea to always serve latest embed.js. So we can instruct user to use Math.random part to fetch emmbed script.

All other assets could be set up to contain chunk hashes in their names that generated at build time.
